export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const manufacturerModels = [
  { name: "Acura", models: ["ILX", "TLX", "RLX", "RDX", "MDX"] },
  { name: "Alfa Romeo", models: ["Giulia", "Stelvio", "4C"] },
  { name: "Aston Martin", models: ["DB11", "DBS Superleggera", "Vantage"] },
  {
    name: "Audi",
    models: [
      "A3",
      "A4",
      "A6",
      "A7",
      "A8",
      "Q3",
      "Q5",
      "Q7",
      "Q8",
      "TT",
      "R8",
      "e-tron",
    ],
  },
  {
    name: "Bentley",
    models: ["Bentayga", "Continental GT", "Flying Spur", "Mulsanne"],
  },
  {
    name: "BMW",
    models: [
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "6 Series",
      "7 Series",
      "8 Series",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "Z4",
      "i3",
      "i8",
    ],
  },
  { name: "Buick", models: ["Enclave", "Encore", "Envision", "LaCrosse"] },
  { name: "Cadillac", models: ["Escalade", "XT4", "XT5", "XT6", "CT4"] },
  {
    name: "Chevrolet",
    models: [
      "Camaro",
      "Corvette",
      "Cruze",
      "Equinox",
      "Impala",
      "Malibu",
      "Silverado",
      "Sonic",
      "Spark",
      "Suburban",
      "Tahoe",
      "Traverse",
      "Trax",
      "Volt",
    ],
  },
  { name: "Chrysler", models: ["300", "Pacifica"] },
  { name: "Citroen", models: ["C3", "C4", "C5", "C6"] },
  { name: "Dodge", models: ["Challenger", "Charger", "Durango", "Journey"] },
  { name: "Ferrari", models: ["488", "F8 Tributo", "SF90 Stradale"] },
  { name: "Fiat", models: ["500", "500L", "500X"] },
  {
    name: "Ford",
    models: [
      "Bronco",
      "EcoSport",
      "Edge",
      "Escape",
      "Expedition",
      "Explorer",
      "F-150",
      "Mustang",
      "Ranger",
      "Transit",
    ],
  },
  { name: "GMC", models: ["Acadia", "Canyon", "Sierra", "Terrain", "Yukon"] },
  {
    name: "Honda",
    models: [
      "Accord",
      "Civic",
      "CR-V",
      "Fit",
      "HR-V",
      "Insight",
      "Odyssey",
      "Passport",
      "Pilot",
      "Ridgeline",
    ],
  },
  {
    name: "Hyundai",
    models: [
      "Accent",
      "Elantra",
      "Ioniq",
      "Kona",
      "Palisade",
      "Santa Fe",
      "Sonata",
      "Tucson",
      "Veloster",
    ],
  },
  { name: "Infiniti", models: ["Q50", "Q60", "QX50", "QX60", "QX80"] },
  {
    name: "Jaguar",
    models: ["E-PACE", "F-PACE", "I-PACE", "XE", "XF", "XJ", "F-TYPE"],
  },
  {
    name: "Jeep",
    models: [
      "Cherokee",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Renegade",
      "Wrangler",
    ],
  },
  {
    name: "Kia",
    models: [
      "Forte",
      "K5",
      "K900",
      "Niro",
      "Optima",
      "Rio",
      "Sedona",
      "Seltos",
      "Sorento",
      "Soul",
      "Sportage",
      "Telluride",
    ],
  },
  { name: "Lamborghini", models: ["Aventador", "Huracan", "Urus"] },
  {
    name: "Land Rover",
    models: ["Defender", "Discovery", "Range Rover", "Range Rover Sport"],
  },
  {
    name: "Lexus",
    models: ["ES", "GS", "IS", "LC", "LS", "LX", "NX", "RC", "RX", "UX"],
  },
  {
    name: "Lincoln",
    models: ["Aviator", "Continental", "Corsair", "Nautilus", "Navigator"],
  },
  { name: "Maserati", models: ["Ghibli", "Levante", "Quattroporte", "MC20"] },
  {
    name: "Mazda",
    models: [
      "Mazda3",
      "Mazda6",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-8",
      "CX-9",
      "MX-5 Miata",
      "MX-30",
    ],
  },
  { name: "McLaren", models: ["540C", "570S", "720S", "Artura"] },
  {
    name: "Mercedes-Benz",
    models: [
      "A-Class",
      "C-Class",
      "E-Class",
      "S-Class",
      "G-Class",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "EQC",
      "EQS",
    ],
  },
  { name: "MINI", models: ["Cooper", "Countryman", "Clubman", "Convertible"] },
  {
    name: "Mitsubishi",
    models: ["Eclipse Cross", "Mirage", "Outlander", "Outlander Sport"],
  },
  {
    name: "Nissan",
    models: [
      "Altima",
      "Armada",
      "Frontier",
      "Kicks",
      "Maxima",
      "Murano",
      "Pathfinder",
      "Rogue",
      "Sentra",
      "Titan",
      "Versa",
    ],
  },
  {
    name: "Porsche",
    models: ["718", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
  },
  {
    name: "Ram",
    models: ["1500", "2500", "3500", "ProMaster", "ProMaster City"],
  },
  { name: "Rolls-Royce", models: ["Ghost", "Phantom", "Cullinan"] },
  {
    name: "Subaru",
    models: [
      "Ascent",
      "BRZ",
      "Crosstrek",
      "Forester",
      "Impreza",
      "Legacy",
      "Outback",
      "WRX",
    ],
  },
  {
    name: "Tesla",
    models: [
      "Model 3",
      "Model S",
      "Model X",
      "Model Y",
      "Cybertruck",
      "Roadster",
    ],
  },
  {
    name: "Toyota",
    models: [
      "4Runner",
      "Avalon",
      "Camry",
      "Corolla",
      "Highlander",
      "Land Cruiser",
      "Prius",
      "RAV4",
      "Sequoia",
      "Sienna",
      "Tacoma",
      "Tundra",
      "Yaris",
    ],
  },
  {
    name: "Volkswagen",
    models: ["Arteon", "Atlas", "Golf", "Jetta", "Passat", "Tiguan", "Touareg"],
  },
  {
    name: "Volvo",
    models: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
  },
];

export const yearsOfProduction = [
  {
    title: "Year",
    value: "",
  },
  {
    title: "2015",
    value: "2015",
  },
  {
    title: "2016",
    value: "2016",
  },
  {
    title: "2017",
    value: "2017",
  },
  {
    title: "2018",
    value: "2018",
  },
  {
    title: "2019",
    value: "2019",
  },
  {
    title: "2020",
    value: "2020",
  },
  {
    title: "2021",
    value: "2021",
  },
  {
    title: "2022",
    value: "2022",
  },
  {
    title: "2023",
    value: "2023",
  },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      {
        title: "How it works",
        url: "/",
      },
      {
        title: "Featured",
        url: "/",
      },
      {
        title: "Partnership",
        url: "/",
      },
      {
        title: "Bussiness Relation",
        url: "/",
      },
    ],
  },
  {
    title: "Company",
    links: [
      {
        title: "Events",
        url: "/",
      },
      {
        title: "Blog",
        url: "/",
      },
      {
        title: "Podcast",
        url: "/",
      },
      {
        title: "Invite a friend",
        url: "/",
      },
    ],
  },
  {
    title: "Socials",
    links: [
      {
        title: "Discord",
        url: "/",
      },
      {
        title: "Instagram",
        url: "/",
      },
      {
        title: "Twitter",
        url: "/",
      },
      {
        title: "Facebook",
        url: "/",
      },
    ],
  },
];
